name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    #- name: Test
     # run: dotnet test --no-build --verbosity normal               
     
    - name: Sonarqube Begin
      run: |
        dotnet tool install --global dotnet-sonarscanner
        dotnet sonarscanner begin /k:"mTeller.Net" /d:sonar.login="${{secrets.mTeller_TOKEN}}" 
      
    - name: Build
      run: dotnet build mTeller.Net/mTeller.sln --configuration Release --no-restore
    
    - name: Sonarqube End
      run: dotnet sonarscanner end /d:sonar.login="${{secrets.mTeller_TOKEN}}"
